import type { Category, EnxovalItem } from './types';

export const DEFAULT_ENXOVAL_TEMPLATE_NAME = 'Lista sugerida de enxoval';

export const DEFAULT_TEMPLATE_CATEGORIES: Category[] = [
  'Cozinha',
  'Eletro Cozinha',
  'Quarto',
  'Banheiro',
  'Sala de Estar',
  'Área de Serviço',
  'Extra'
];

export const DEFAULT_TEMPLATE_ITEMS: Array<{ name: string; category: Category }> = [
  { name: 'Abridor de Garrafa', category: 'Cozinha' },
  { name: 'Afiador de Facas', category: 'Cozinha' },
  { name: 'Abridor de Latas', category: 'Cozinha' },
  { name: 'Açucareiro', category: 'Cozinha' },
  { name: 'Amassador de Batata', category: 'Cozinha' },
  { name: 'Amassador de Feijão', category: 'Cozinha' },
  { name: 'Jogo de Xícaras', category: 'Cozinha' },
  { name: 'Jogo de Sobremesa', category: 'Cozinha' },
  { name: 'Jogo de Copo P', category: 'Cozinha' },
  { name: 'Jogo de Copo M', category: 'Cozinha' },
  { name: 'Jogo de Copo G', category: 'Cozinha' },
  { name: 'Jogo de Taças', category: 'Cozinha' },
  { name: 'Jogo de Talheres', category: 'Cozinha' },
  { name: 'Porta Pão', category: 'Cozinha' },
  { name: 'Pratos Rasos', category: 'Cozinha' },
  { name: 'Pratos Fundos', category: 'Cozinha' },
  { name: 'Faqueiro Tramontina', category: 'Cozinha' },
  { name: 'Colheres de Silicone', category: 'Cozinha' },
  { name: 'Colheres de Pau', category: 'Cozinha' },
  { name: 'Saladeira', category: 'Cozinha' },
  { name: 'Travessas', category: 'Cozinha' },
  { name: 'Forma de Bolo', category: 'Cozinha' },
  { name: 'Forma Retangular', category: 'Cozinha' },
  { name: 'Potes de Vidro', category: 'Cozinha' },
  { name: 'Potes de Plástico', category: 'Cozinha' },
  { name: 'Bandejas', category: 'Cozinha' },
  { name: 'Forma de Silicone', category: 'Cozinha' },
  { name: 'Garrafa Térmica', category: 'Cozinha' },
  { name: 'Garrafa de Água', category: 'Cozinha' },
  { name: 'Jarra de Suco', category: 'Cozinha' },
  { name: 'Chaleira', category: 'Cozinha' },
  { name: 'Bule', category: 'Cozinha' },
  { name: 'Saleiro', category: 'Cozinha' },
  { name: 'Petisqueira', category: 'Cozinha' },
  { name: 'Bomboniere', category: 'Cozinha' },
  { name: 'Mantegueira', category: 'Cozinha' },
  { name: 'Porta Temperos', category: 'Cozinha' },
  { name: 'Tábua de Carne', category: 'Cozinha' },
  { name: 'Frigideira', category: 'Cozinha' },
  { name: 'Frigideira Pequena', category: 'Cozinha' },
  { name: 'Descascador de Legumes', category: 'Cozinha' },
  { name: 'Ralador', category: 'Cozinha' },
  { name: 'Escorredor de Louça', category: 'Cozinha' },
  { name: 'Lixeira de Cozinha', category: 'Cozinha' },
  { name: 'Fruteira', category: 'Cozinha' },
  { name: 'Descanso de Panela', category: 'Cozinha' },
  { name: 'Descanso de Prato', category: 'Cozinha' },
  { name: 'Suporte Papel Toalha', category: 'Cozinha' },
  { name: 'Porta Guardanapo', category: 'Cozinha' },
  { name: 'Porta Copos', category: 'Cozinha' },
  { name: 'Tapete de Cozinha', category: 'Cozinha' },
  { name: 'Espátula', category: 'Cozinha' },
  { name: 'Escumadeira', category: 'Cozinha' },
  { name: 'Concha', category: 'Cozinha' },
  { name: 'Copo Medidor', category: 'Cozinha' },
  { name: 'Espremedor', category: 'Cozinha' },
  { name: 'Escorredor de Macarrão', category: 'Cozinha' },
  { name: 'Forma para Gelo', category: 'Cozinha' },
  { name: 'Jogo de Peneiras', category: 'Cozinha' },
  { name: 'Leiteira', category: 'Cozinha' },
  { name: 'Paliteiro', category: 'Cozinha' },
  { name: 'Panos de Prato', category: 'Cozinha' },
  { name: 'Pegador de Salada', category: 'Cozinha' },
  { name: 'Pincel', category: 'Cozinha' },
  { name: 'Tesoura', category: 'Cozinha' },
  { name: 'Porta Mantimentos', category: 'Cozinha' },
  { name: 'Queijeira', category: 'Cozinha' },
  { name: 'Rodo de Pia', category: 'Cozinha' },
  { name: 'Rolo de Abrir Massa', category: 'Cozinha' },
  { name: 'Secador de Salada', category: 'Cozinha' },
  { name: 'Tábua para Frios', category: 'Cozinha' },
  { name: 'Suporte de Bolo', category: 'Cozinha' },
  { name: 'Bacias de Plástico', category: 'Cozinha' },
  { name: 'Borrifador de Azeite', category: 'Cozinha' },
  { name: 'Colheres de Medida', category: 'Cozinha' },
  { name: 'Cortador de Bolo', category: 'Cozinha' },
  { name: 'Cortador de Pizza', category: 'Cozinha' },
  { name: 'Triturador Pequeno', category: 'Cozinha' },
  { name: 'Funil', category: 'Cozinha' },
  { name: 'Martelo de Carne', category: 'Cozinha' },
  { name: 'Panela Cuscuzeira', category: 'Cozinha' },
  { name: 'Jogo de Panelas Tramontina', category: 'Cozinha' },
  { name: 'Saca Rolha', category: 'Cozinha' },
  { name: 'Porta Alho', category: 'Cozinha' },
  { name: 'Timer de Ovo', category: 'Cozinha' },
  { name: 'Organizador de Talheres', category: 'Cozinha' },
  { name: 'Pipoqueira', category: 'Cozinha' },
  { name: 'Panela de Pressão', category: 'Cozinha' },
  { name: 'Cestos Organizadores', category: 'Cozinha' },
  { name: 'Cumbucas', category: 'Cozinha' },
  { name: 'Luva Térmica (Forno)', category: 'Cozinha' },
  { name: 'Organizadores de Geladeira', category: 'Cozinha' },
  { name: 'Socador de Tempero', category: 'Cozinha' },
  { name: 'Porta Frios', category: 'Cozinha' },
  { name: 'Air Fryer', category: 'Eletro Cozinha' },
  { name: 'Liquidificador', category: 'Eletro Cozinha' },
  { name: 'Microondas', category: 'Eletro Cozinha' },
  { name: 'Batedeira', category: 'Eletro Cozinha' },
  { name: 'Sanduicheira', category: 'Eletro Cozinha' },
  { name: 'Processador de Alimentos', category: 'Eletro Cozinha' },
  { name: 'Purificador de Água', category: 'Eletro Cozinha' },
  { name: 'Cooktop', category: 'Eletro Cozinha' },
  { name: 'Forno', category: 'Eletro Cozinha' },
  { name: 'Geladeira', category: 'Eletro Cozinha' },
  { name: 'Lava Louça', category: 'Eletro Cozinha' },
  { name: 'Mixer', category: 'Eletro Cozinha' },
  { name: 'Seladora a Vácuo', category: 'Eletro Cozinha' },
  { name: 'Abajur', category: 'Quarto' },
  { name: 'Cabeceira', category: 'Quarto' },
  { name: 'Cabides', category: 'Quarto' },
  { name: 'Cobertor Casal', category: 'Quarto' },
  { name: 'Cobertor Solteiro', category: 'Quarto' },
  { name: 'Mantinha Casal', category: 'Quarto' },
  { name: 'Mantinha Solteiro', category: 'Quarto' },
  { name: 'Caixa Organizadora', category: 'Quarto' },
  { name: 'Jogo de Colcha', category: 'Quarto' },
  { name: 'Fronha Básica', category: 'Quarto' },
  { name: 'Colchão', category: 'Quarto' },
  { name: 'Cama', category: 'Quarto' },
  { name: 'Cortina', category: 'Quarto' },
  { name: 'Decoração', category: 'Quarto' },
  { name: 'Lençol', category: 'Quarto' },
  { name: 'Manta', category: 'Quarto' },
  { name: 'Mesinha de Cabeceira', category: 'Quarto' },
  { name: 'Protetor de Colchão', category: 'Quarto' },
  { name: 'Travesseiro', category: 'Quarto' },
  { name: 'Tapete', category: 'Quarto' },
  { name: 'Guarda-roupa', category: 'Quarto' },
  { name: 'Espelho', category: 'Quarto' },
  { name: 'Almofadas', category: 'Quarto' },
  { name: 'Ventilador', category: 'Quarto' },
  { name: 'Ar Condicionado', category: 'Quarto' },
  { name: 'Penteadeira', category: 'Quarto' },
  { name: 'Televisão', category: 'Quarto' },
  { name: 'Antena SKY', category: 'Quarto' },
  { name: 'Armário de Pia', category: 'Banheiro' },
  { name: 'Box', category: 'Banheiro' },
  { name: 'Chuveiro', category: 'Banheiro' },
  { name: 'Cesto de Roupa Suja', category: 'Banheiro' },
  { name: 'Decoração', category: 'Banheiro' },
  { name: 'Ducha Higiênica', category: 'Banheiro' },
  { name: 'Escova de Sanitário', category: 'Banheiro' },
  { name: 'Espelho', category: 'Banheiro' },
  { name: 'Frasco Sabonete Líquido', category: 'Banheiro' },
  { name: 'Lixeira', category: 'Banheiro' },
  { name: 'Porta Cotonete', category: 'Banheiro' },
  { name: 'Porta Escova de Dente', category: 'Banheiro' },
  { name: 'Porta Papel Higiênico', category: 'Banheiro' },
  { name: 'Porta Toalha', category: 'Banheiro' },
  { name: 'Rodo', category: 'Banheiro' },
  { name: 'Saboneteira', category: 'Banheiro' },
  { name: 'Tapetes', category: 'Banheiro' },
  { name: 'Toalha de Banho', category: 'Banheiro' },
  { name: 'Toalha de Rosto', category: 'Banheiro' },
  { name: 'Abajur', category: 'Sala de Estar' },
  { name: 'Almofadas', category: 'Sala de Estar' },
  { name: 'Capas de Almofadas', category: 'Sala de Estar' },
  { name: 'Manta de Sofá', category: 'Sala de Estar' },
  { name: 'Mesa de Canto', category: 'Sala de Estar' },
  { name: 'Mesa de Centro', category: 'Sala de Estar' },
  { name: 'Painel de TV', category: 'Sala de Estar' },
  { name: 'Poltrona', category: 'Sala de Estar' },
  { name: 'Porta Chaves', category: 'Sala de Estar' },
  { name: 'Porta Retratos', category: 'Sala de Estar' },
  { name: 'Sofá', category: 'Sala de Estar' },
  { name: 'Tapete', category: 'Sala de Estar' },
  { name: 'Televisão', category: 'Sala de Estar' },
  { name: 'Mesa e Cadeira', category: 'Sala de Estar' },
  { name: 'Cortinas', category: 'Sala de Estar' },
  { name: 'Decoração', category: 'Sala de Estar' },
  { name: 'Armário Multiuso', category: 'Área de Serviço' },
  { name: 'Aspirador de Pó', category: 'Área de Serviço' },
  { name: 'Robô Aspirador', category: 'Área de Serviço' },
  { name: 'Balde', category: 'Área de Serviço' },
  { name: 'Borrifador', category: 'Área de Serviço' },
  { name: 'Dispenser de Sabão', category: 'Área de Serviço' },
  { name: 'Escada', category: 'Área de Serviço' },
  { name: 'Escovão', category: 'Área de Serviço' },
  { name: 'Ferro de Passar', category: 'Área de Serviço' },
  { name: 'Flanelas', category: 'Área de Serviço' },
  { name: 'Pá de Lixo', category: 'Área de Serviço' },
  { name: 'Pano de Chão', category: 'Área de Serviço' },
  { name: 'Potes Organizadores', category: 'Área de Serviço' },
  { name: 'Prendedor de Roupa', category: 'Área de Serviço' },
  { name: 'Rodo', category: 'Área de Serviço' },
  { name: 'Suporte de Vassoura', category: 'Área de Serviço' },
  { name: 'Vassoura', category: 'Área de Serviço' },
  { name: 'Varal', category: 'Área de Serviço' },
  { name: 'Mop', category: 'Área de Serviço' },
  { name: 'Máquina de Lavar', category: 'Área de Serviço' },
  { name: 'Secadora', category: 'Área de Serviço' },
  { name: 'Extensão', category: 'Área de Serviço' },
  { name: 'Adaptador de Tomada', category: 'Área de Serviço' },
  { name: 'Lixeira', category: 'Área de Serviço' },
  { name: 'Bacia', category: 'Área de Serviço' },
  { name: 'Porta Amaciante', category: 'Área de Serviço' },
  { name: 'Pá', category: 'Área de Serviço' },
  { name: 'Desentupidor', category: 'Área de Serviço' },
  { name: 'Aromatizante de Ambiente', category: 'Área de Serviço' }
];

const generateId = () => Math.random().toString(36).slice(2, 11);
const fallbackCategoryId = (category: Category) => category.toLowerCase().replace(/\s+/g, '-');
const fallbackUpdatedAt = new Date(0).toISOString();

export const defaultItems: EnxovalItem[] = DEFAULT_TEMPLATE_ITEMS.map((item, index) => ({
  id: generateId(),
  name: item.name,
  categoryId: fallbackCategoryId(item.category),
  category: item.category,
  checked: false,
  link: '',
  description: '',
  priceCents: null,
  sortOrder: index,
  updatedAt: fallbackUpdatedAt
}));
